# Generated by Django 4.2.1 on 2023-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_plantdb_plantimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_image', models.ImageField(default='null.jpg', upload_to='image')),
                ('plantname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
